export const SKILLS = [
  {
    cat: "Languages",
    icon: "⌨️",
    color: "#3B82F6",
    tags: ["Python", "C++", "JavaScript", "TypeScript", "Java"],
  },
  {
    cat: "AI / ML",
    icon: "🤖",
    color: "#8B5CF6",
    tags: ["TensorFlow", "PyTorch", "Scikit-learn", "LangChain", "XGBoost", "RAG", "Multi-Agent", "LLM Integration"],
  },
  {
    cat: "Web & Backend",
    icon: "⚙️",
    color: "#10B981",
    tags: ["FastAPI", "Node.js", "REST APIs", "JWT Auth", "Microservices", "WebSockets", "Postman"],
  },
  {
    cat: "Frontend",
    icon: "🖥️",
    color: "#F59E0B",
    tags: ["React.js", "Next.js", "Tailwind CSS", "Socket.IO", "Streamlit"],
  },
  {
    cat: "Databases",
    icon: "🗄️",
    color: "#06B6D4",
    tags: ["PostgreSQL", "MongoDB", "Redis", "PostGIS", "SQL"],
  },
  {
    cat: "DevOps & Cloud",
    icon: "☁️",
    color: "#F43F5E",
    tags: ["Docker", "Kubernetes", "AWS EC2", "AWS S3", "CI/CD", "GitHub Actions"],
  },
  {
    cat: "Blockchain",
    icon: "⛓️",
    color: "#F59E0B",
    tags: ["BNB Smart Chain", "NFT Minting", "Solidity basics"],
  },
  {
    cat: "Tools & Libs",
    icon: "🔧",
    color: "#10B981",
    tags: ["NumPy", "Pandas", "Git", "Linux", "MCP Protocol", "YOLOv8", "Mapbox"],
  },
];

export const PROJECTS = [
  {
    emoji: "🚆",
    bg: "rgba(59,130,246,0.12)",
    accent: "#3B82F6",
    badge: "Java · Full Stack",
    name: "RailConnect – Smart Railway Reservation",
    desc: "Full-stack railway reservation platform automating the complete ticket booking lifecycle with an intelligent seat allocation engine, concurrent booking safety, and unique PNR generation.",
    stack: ["Java", "Spring Boot", "Spring Security", "JWT", "PostgreSQL", "React.js", "Tailwind CSS", "Swagger"],
    featured: true,
    details: {
      type: "Individual", status: "Complete",
      github: null,
      problem: "Traditional railway booking systems suffer from seat conflicts under concurrent load, manual coach management, and insecure authentication — making them fragile at enterprise scale.",
      contributions: [
        "Designed an intelligent seat allocation engine that auto-generates coaches and prevents race-condition double-bookings",
        "Implemented PNR generation system with unique, collision-free ticket identifiers",
        "Built role-based access control (RBAC) using Spring Security + JWT for admin and passenger portals",
        "Developed full booking lifecycle: search → reserve → cancel → refund with atomic DB transactions",
        "Exposed RESTful APIs documented via Swagger UI for admin and client consumers",
      ],
      metrics: [
        { label: "Booking Lifecycle", value: "Fully Automated" },
        { label: "Auth", value: "JWT + Spring Security" },
        { label: "Concurrency", value: "Race-condition safe" },
        { label: "Project Type", value: "Individual" },
      ],
      stackDetails: [
        "Java 21 + Spring Boot 3 for core backend services",
        "Spring Security with stateless JWT authentication",
        "PostgreSQL with optimistic locking for seat reservation",
        "React.js + Tailwind CSS + ShadCN/UI frontend",
        "Swagger / OpenAPI 3 documentation",
      ],
    },
  },
  {
    emoji: "💳",
    bg: "rgba(244,63,94,0.12)",
    accent: "#F43F5E",
    badge: "AI/ML · FinTech",
    name: "Real-Time Fraud Detection System",
    desc: "AI-powered platform detecting fraudulent transactions via dynamic risk scoring — analyzing behavior, device fingerprints, and geolocation with XGBoost + Random Forest inference.",
    stack: ["Python", "FastAPI", "Docker", "PostgreSQL", "XGBoost", "Random Forest", "Redis", "Kafka"],
    featured: true,
    details: {
      type: "Individual", status: "Complete",
      github: null,
      problem: "Rule-based fraud detectors miss novel attack patterns and flag too many false positives, causing genuine customers to be blocked while sophisticated fraud slips through.",
      contributions: [
        "Built dynamic risk scoring engine combining XGBoost + Random Forest ensemble models",
        "Engineered behavioral analytics features: transaction velocity, geo-deviation, device fingerprinting",
        "Developed low-latency FastAPI inference layer with sub-50ms response times",
        "Containerized full stack with Docker Compose for reproducible deployment",
        "Designed roadmap integrating Redis for feature caching and Kafka for real-time event streaming",
      ],
      metrics: [
        { label: "Inference Latency", value: "< 50ms" },
        { label: "Model", value: "XGBoost + RF Ensemble" },
        { label: "Signals", value: "Behavior + Geo + Device" },
        { label: "Deployment", value: "Dockerized Microservice" },
      ],
      stackDetails: [
        "XGBoost + Random Forest ensemble for risk scoring",
        "FastAPI for low-latency REST inference endpoints",
        "PostgreSQL for transaction history and audit logs",
        "Docker Compose for portable service orchestration",
        "Redis (roadmap) for sub-ms feature cache; Kafka for event ingestion at scale",
      ],
    },
  },
  {
    emoji: "🚌",
    bg: "rgba(16,185,129,0.12)",
    accent: "#10B981",
    badge: "GenAI · RAG",
    name: "VoltTransit – AI Emergency RAG Engine",
    desc: "Safety-critical AI assistant generating verified emergency response checklists for EV transit operators using Retrieval-Augmented Generation with hallucination prevention.",
    stack: ["FastAPI", "LangChain", "ChromaDB", "Sentence Transformers", "Python", "Docker"],
    featured: true,
    details: {
      type: "Individual", status: "Ongoing",
      github: null,
      problem: "LLMs hallucinate safety-critical procedures, making them dangerous for emergency response in public transit. Operators need verifiable, source-traced checklists — not LLM guesses.",
      contributions: [
        "Implemented section-aware semantic chunking of EV safety manuals for precise retrieval",
        "Built vector search pipeline with ChromaDB + Sentence Transformers and similarity thresholding",
        "Engineered hallucination prevention: responses trace back to source document passages",
        "Added Retrieval@K evaluation framework to measure retrieval quality",
        "Designed human-escalation mechanism for edge cases below confidence threshold",
      ],
      metrics: [
        { label: "Architecture", value: "RAG Pipeline" },
        { label: "Hallucination Guard", value: "Source Tracing" },
        { label: "Escalation", value: "Human-in-the-loop" },
        { label: "Status", value: "Ongoing" },
      ],
      stackDetails: [
        "LangChain orchestration with custom RAG chain",
        "ChromaDB vector store for EV manual embeddings",
        "Sentence Transformers for semantic similarity scoring",
        "FastAPI backend with Docker containerization",
        "Retrieval@K eval + similarity threshold gating",
      ],
    },
  },
  {
    emoji: "🎟️",
    bg: "rgba(245,158,11,0.1)",
    accent: "#F59E0B",
    badge: "Distributed Systems · Backend",
    name: "Distributed Event-Driven Ticketing Engine",
    desc: "High-performance flash-sale pipeline with strict consistency — decouples inventory reservation from async payment settlement using Kafka, Redis, and the Transactional Outbox Pattern.",
    stack: ["Java", "Spring Boot", "PostgreSQL", "Redis", "Apache Kafka", "Debezium", "Docker", "Prometheus", "Grafana"],
    featured: true,
    details: {
      type: "Individual", status: "Complete",
      github: null,
      problem: "Flash sales cause thundering-herd gridlock: connection pool exhaustion, race-condition double-bookings, and distributed transaction bottlenecks that lead to overselling under load.",
      contributions: [
        "Designed Redis Lua scripting for atomic inventory allocation, eliminating race conditions",
        "Implemented Transactional Outbox Pattern via Debezium CDC for guaranteed at-least-once event delivery",
        "Separated high-speed inventory reservation from async payment settlement with Kafka topics",
        "Built Distributed Saga compensation logic for payment failure rollback",
        "Configured Prometheus + Grafana observability stack with custom flash-sale dashboards",
      ],
      metrics: [
        { label: "Target Throughput", value: "10,000+ RPS" },
        { label: "Overselling Rate", value: "0.00%" },
        { label: "Event Delivery", value: "At-least-once" },
        { label: "Observability", value: "Prometheus + Grafana" },
      ],
      stackDetails: [
        "Kafka Connect + Debezium for WAL-tailing CDC",
        "Redis with atomic Lua scripts for inventory reservation",
        "PostgreSQL with Transactional Outbox for event sourcing",
        "Spring Boot Saga orchestration for payment compensation",
        "Prometheus metrics + Grafana dashboards for SLA monitoring",
      ],
    },
  },
  {
    emoji: "🏥",
    bg: "rgba(139,92,246,0.1)",
    accent: "#8B5CF6",
    badge: "GenAI · Healthcare",
    name: "AI Multi-Agent Healthcare Platform",
    desc: "Multi-agent LangChain system assisting clinicians in diabetes risk assessment — orchestrating specialist agents for report analysis, risk prediction, and emergency alerting.",
    stack: ["LangChain", "FastAPI", "PostgreSQL", "MongoDB", "Python"],
    featured: true,
    details: {
      type: "Team", status: "Complete",
      github: null,
      problem: "Clinicians waste hours manually reviewing patient reports and lack an automated system to flag high-risk diabetes cases for immediate escalation.",
      contributions: [
        "Developed the Report Analyzer agent for extracting clinical insights from medical PDFs",
        "Built the Master Orchestrator agent coordinating specialist sub-agents in a pipeline",
        "Engineered the Alert Agent for real-time emergency escalation on high-risk predictions",
        "Implemented secure FastAPI backend with JWT authentication and HIPAA-aligned data handling",
        "Integrated PostgreSQL + MongoDB hybrid storage for structured vitals and unstructured report data",
      ],
      metrics: [
        { label: "Project Type", value: "Team Project" },
        { label: "Agent Architecture", value: "Multi-Agent (LangChain)" },
        { label: "Auth", value: "JWT Secured" },
        { label: "Storage", value: "PostgreSQL + MongoDB" },
      ],
      stackDetails: [
        "LangChain multi-agent orchestration with tool-use",
        "FastAPI with JWT auth for secure clinical API endpoints",
        "PostgreSQL for structured patient vitals and history",
        "MongoDB for unstructured medical report storage",
        "Python ML models for diabetes risk probability scoring",
      ],
    },
  },
  {
    emoji: "🧬",
    bg: "rgba(6,182,212,0.1)",
    accent: "#06B6D4",
    badge: "Bioinformatics · Web3",
    name: "VA-2 Genomic Data Analysis Platform",
    desc: "AI + blockchain platform combining Evo 2 genomic foundation model fine-tuning with BNB Smart Chain provenance for secure, ownership-tracked genomic research.",
    stack: ["FastAPI", "PostgreSQL", "Evo 2", "Python", "BNB Smart Chain"],
    featured: true,
    details: {
      type: "Team", status: "Complete",
      github: null,
      problem: "Genomic research outputs lack verifiable ownership and chain-of-custody, making it impossible to attribute discoveries or prevent data theft in collaborative environments.",
      contributions: [
        "Fine-tuned the Evo 2 genomic foundation model for variant-specific sequence analysis",
        "Built genomic preprocessing pipelines: quality filtering, sequence normalization, variant calling",
        "Designed and implemented FastAPI backend endpoints for genomic data submission and retrieval",
        "Integrated BNB Smart Chain for blockchain-backed NFT minting of research outputs",
        "Designed PostgreSQL schema for multi-user genomic dataset management",
      ],
      metrics: [
        { label: "Foundation Model", value: "Evo 2 (Fine-tuned)" },
        { label: "Blockchain", value: "BNB Smart Chain" },
        { label: "Hackathon", value: "🏅 4th Place — International" },
        { label: "Type", value: "Team Project" },
      ],
      stackDetails: [
        "Evo 2 genomic foundation model with task-specific fine-tuning",
        "FastAPI for RESTful genomic data ingestion and analysis APIs",
        "BNB Smart Chain + NFT minting for research provenance",
        "PostgreSQL relational schema for multi-user dataset tracking",
        "Python bioinformatics pipeline: FASTQ processing + variant annotation",
      ],
    },
  },
  {
    emoji: "💧",
    bg: "rgba(59,130,246,0.08)",
    accent: "#3B82F6",
    badge: "Smart India Hackathon · Mobile",
    name: "Groundwater Resource Evaluation System",
    desc: "SIH mobile app enabling government agencies to monitor groundwater via DWLR station data — featuring GIS maps, real-time analytics, and alert interfaces for Android and iOS.",
    stack: ["React Native", "Expo", "TypeScript", "Expo Router"],
    featured: true,
    details: {
      type: "Team", status: "Complete",
      github: null,
      problem: "Government groundwater agencies rely on manual DWLR readings with no centralized dashboard, making it impossible to detect water-level anomalies or trigger timely alerts.",
      contributions: [
        "Designed and built the entire React Native dashboard from scratch",
        "Implemented interactive GIS-based map for visualizing DWLR station coverage",
        "Built real-time water-level charts with trend analytics and anomaly highlighting",
        "Developed alert notification system for groundwater level threshold breaches",
        "Ensured cross-platform compatibility for both Android and iOS via Expo",
      ],
      metrics: [
        { label: "Platform", value: "Android + iOS" },
        { label: "Event", value: "Smart India Hackathon" },
        { label: "Frontend", value: "React Native + Expo" },
        { label: "Type", value: "Team Project" },
      ],
      stackDetails: [
        "React Native with Expo managed workflow",
        "TypeScript for type-safe component development",
        "Expo Router for file-based navigation",
        "GIS integration for DWLR station mapping",
        "Charting libraries for real-time water level visualization",
      ],
    },
  },
];

export const HACKATHONS = [
  {
    name: "BNB Chain Hackathon",
    org: "BNB Chain — International",
    result: "🏅 4th Place — DSCI Track",
    type: "gold",
    desc: "Honored for the VA-2 Genomic Platform combining Evo 2 fine-tuning with blockchain-based NFT ownership. Competed globally.",
  },
  {
    name: "Cyber Hackathon",
    org: "Nagpur Police Commissionerate",
    result: "🥈 5th Place / 40 Teams",
    type: "silver",
    desc: "Top 5 among 40 finalist teams solving real-world cybersecurity challenges posed by the Nagpur Police.",
  },
  {
    name: "Smart India Hackathon (SIH)",
    org: "Ministry of Education, India",
    result: "🇮🇳 National Participant",
    type: "blue",
    desc: "India's largest hackathon — tackled problem statements issued by government ministries and PSUs.",
  },
  {
    name: "Enigma",
    org: "Collegiate Tech Hackathon",
    result: "💡 Participant",
    type: "purple",
    desc: "Built rapid prototypes for challenging tech problem statements under tight collegiate competition conditions.",
  },
  {
    name: "HACKHAZARD '25",
    org: "Innovation Build Challenge",
    result: "⚡ Participant",
    type: "emerald",
    desc: "Fast-paced full-stack build challenge — designed, built and pitched complete solutions in hours.",
  },
];

export const ACHIEVEMENTS = [
  {
    icon: "🏛️",
    title: "ACM Chapter Secretary",
    desc: "Secretary of ACM Student Chapter at YCCE. Previously served as Webmaster, managing the chapter website and organizing technical events, workshops, and coding activities for 200+ members.",
  },
  {
    icon: "🥇",
    title: "BNB Hackathon — 4th Place",
    desc: "Received an Honorable Mention in the DSCI Track at the International BNB Chain Hackathon for developing a blockchain-powered genomic analysis platform.",
  },
  {
    icon: "🛡️",
    title: "Cyber Hackathon — Top 5",
    desc: "Secured a Top 5 position among 40 finalist teams in the Nagpur Police Commissionerate Cybersecurity Hackathon.",
  },
  {
    icon: "🍃",
    title: "MongoDB Python Developer Path",
    desc: "Successfully completed MongoDB University's Python Developer learning path covering CRUD operations, aggregation pipelines, indexing, schema design, and MongoDB-Python integration.",
  },
  {
    icon: "💻",
    title: "DSA in C++ Certification",
    desc: "Completed Data Structures & Algorithms training focused on sorting, searching, trees, graphs, dynamic programming, and advanced problem-solving techniques.",
  },
  {
    icon: "🌊",
    title: "Smart India Hackathon",
    desc: "Developed a Real-Time Groundwater Resource Evaluation platform using DWLR data to support groundwater monitoring, analytics, and sustainable water management.",
  },
  {
    icon: "🏐",
    title: "Volleyball & Travel",
    desc: "Active volleyball player and avid traveler. These experiences strengthen teamwork, adaptability, leadership, and discipline beyond engineering.",
  },
];

export const RESULT_STYLE = {
  gold:    { bg:"rgba(245,158,11,.12)",   color:"#FCD34D", bdr:"rgba(245,158,11,.25)"   },
  silver:  { bg:"rgba(148,163,184,.1)",   color:"#94A3B8", bdr:"rgba(148,163,184,.2)"   },
  blue:    { bg:"rgba(59,130,246,.1)",    color:"#93C5FD", bdr:"rgba(59,130,246,.2)"    },
  purple:  { bg:"rgba(139,92,246,.1)",    color:"#C4B5FD", bdr:"rgba(139,92,246,.2)"    },
  emerald: { bg:"rgba(16,185,129,.1)",    color:"#6EE7B7", bdr:"rgba(16,185,129,.2)"    },
};

export const TECH_MARQUEE = [
  "Python", "FastAPI", "React", "Next.js", "Node.js", "Docker",
  "PostgreSQL", "MongoDB", "LangChain", "TensorFlow", "AWS", "Kubernetes",
  "TypeScript", "XGBoost", "Redis", "JWT", "CI/CD", "YOLOv8",
  "Tailwind", "REST APIs", "Git", "Linux", "Postman", "Pandas",
];